node {

  stage("Build Fibonacci") {
    sh """
      git clone --depth 1 "https://github.com/alfpedraza-aws-devops/fibonacci"
      ./jenkins/jobs/aws-devops/build-image.sh \
        ${params.REGION_NAME} \
        ${params.ECR_URL} \
        "aws-devops-fibonacci" \
        "0.1.4" \
        ${env.BUILD_ID}
    """
  }

  stage("Build Kubernetes API") {
    sh """
      git clone --depth 1 "https://github.com/alfpedraza-aws-devops/kubernetes-api"
      ./jenkins/jobs/aws-devops/build-image.sh \
        ${params.REGION_NAME} \
        ${params.ECR_URL} \
        "aws-devops-kubernetes-api" \
        "0.1.11" \
        ${env.BUILD_ID}
    """
  }

  stage("Build Web UI") {
    sh """
      git clone --depth 1 "https://github.com/alfpedraza-aws-devops/web-ui"
      ./jenkins/jobs/aws-devops/build-image.sh \
        ${params.REGION_NAME} \
        ${params.ECR_URL} \
        "aws-devops-web-ui" \
        "0.1.4" \
        ${env.BUILD_ID}
    """
  }

  stage("Update VPC") {
    withCredentials([usernamePassword(credentialsId: "aws_credentials", usernameVariable: "AWS_ACCESS_KEY_ID", passwordVariable: "AWS_SECRET_ACCESS_KEY")]) {
      sh """
        git clone --depth 1 "https://github.com/alfpedraza-aws-devops/deployment"
        cd ./vpc
        ./jenkins/jobs/aws-devops/apply-terraform.sh \
          ${params.ACCOUNT_ID} \
          ${params.REGION_NAME} \
          ${params.PROJECT_NAME} \
          "vpc"
      """
    }
  }

  stage("Update DEV environment") {
    withCredentials([usernamePassword(credentialsId: "aws_credentials", usernameVariable: "AWS_ACCESS_KEY_ID", passwordVariable: "AWS_SECRET_ACCESS_KEY")]) {
      sh """
        git clone --depth 1 "https://github.com/alfpedraza-aws-devops/deployment"
        cd ./vpc
        ./jenkins/jobs/aws-devops/apply-terraform.sh \
          ${params.ACCOUNT_ID} \
          ${params.REGION_NAME} \
          ${params.PROJECT_NAME} \
          "dev"
      """
    }
  }

  stage("Deploy to DEV environment") {
    echo "Deploy to DEV environment"
  }

  stage("Production Approval") {
    input "Deploy to PROD?"
  }

  stage("Update PROD environment") {
    withCredentials([usernamePassword(credentialsId: "aws_credentials", usernameVariable: "AWS_ACCESS_KEY_ID", passwordVariable: "AWS_SECRET_ACCESS_KEY")]) {
      sh """
        git clone --depth 1 "https://github.com/alfpedraza-aws-devops/deployment"
        cd ./vpc
        ./jenkins/jobs/aws-devops/apply-terraform.sh \
          ${params.ACCOUNT_ID} \
          ${params.REGION_NAME} \
          ${params.PROJECT_NAME} \
          "prod"
      """
    }
  }

  stage("Deploy to PROD environment") {
    echo "Deploy to PROD environment"
  }
  
}