---
# Install the python-jenkins package. Required to run "jenkins_job" task

- name: Add the Python-Jenkins yum repository
  yum_repository:
    name: pythonjenkins_repo
    description: Python Jenkins Package Repository
    baseurl: https://download-ib01.fedoraproject.org/pub/epel/7/aarch64/
    state: present

- name: Import the Python-Jenkins repository GPG key
  rpm_key:
    key: https://download-ib01.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    state: present

- name: Install the Python-Jenkins package
  yum:
    name: python-jenkins-0.4.14-2.el7.noarch
    state: present

# Install the Jenkins job

- name: Start the Jenkins service so the plugins can be installed
  service:
    name: jenkins
    enabled: yes
    state: started

- name: Wait until the Jenkins service is available
  uri:
    url: "http://localhost:8080/"
    return_content: yes
    status_code: [200, 404]
  register: jenkins_wait
  until: jenkins_wait.status == 200 and jenkins_wait.content.find('Please wait while Jenkins is getting ready to work') == -1
  retries: 10
  delay: 5

- name: Create a Jenkins job to run a pipeline
  jenkins_job:
    name: "{{ jenkins_job_name }}"
    config: "{{ lookup('template', 'templates/job-config.xml.j2') }}"
    state: present