---
# Install the Jenkins job

- name: Create a Jenkins job to run a pipeline
  jenkins_job:
    name: "{{ jenkins_job_name }}"
    config: "{{ lookup('template', 'templates/job-config.xml.j2') }}"
    state: present