---
## Git
#- name: Add Docker repository
#  yum_repository:
#    name: docker_repo
#    description: Docker Package Repository
#    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
#- name: Import Docker GPG key 
#  rpm_key:  
#    state: present 
#    key: https://download.docker.com/linux/centos/gpg
#- name: Install Docker 
#  yum:
#    name: docker-ce-18.09.9-3.el7.x86_64
#    state: present

# Kubectl
#- name: Add Kubernetes repository
#  yum_repository:
#    name: kubernetes_repo
#    description: Kubernetes Package Repository
#    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/
#- name: Import Kubernetes GPG key
#  rpm_key:
#    state: present
#    key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
#- name: Install Kubectl
#  yum:
#    name: kubectl-1.10.3-0.x86_64 
#    state: present

# Helm
- name: Create temporal folder
  command:
    cmd: mkdir -p /tmp/aws-devops/helm
    creates: /usr/local/bin/helm
- name: Download helm binary
  unarchive:
    src: https://get.helm.sh/helm-v2.7.2-linux-amd64.tar.gz
    dest: /tmp/aws-devops/helm
    creates: /usr/local/bin/helm
    remote_src: yes
- name: Move helm binary into place.
  command:
    cmd: cp /tmp/aws-devops/helm/linux-amd64/helm /usr/local/bin/helm
    creates: /usr/local/bin/helm

#- name: Install Helm
#  yum:
#    name: helm  2.7.2
#    state: present
#
#- name: Install Terraform
#  yum:
#    name: terraform 0.12.20
#    state: present
#
#- name: Install AWS
#  yum:
#    name: aws aws-cli/2.0.0 Python/3.7.3 Linux/5.0.0-1032-azure botocore/2.0.0dev4 
#    state: present
#
#- name: Install Jenkins
#  yum:
#    name: jenkins jenkins-2.220-1.1
#    state: present