---
## Unzip
#- name: Download unzip 6.0
#  yum:
#    name: unzip-6.0-20.el7.x86_64
#    state: present
#- name: Display debug information
#  debug:
#    msg: unzip 6.0 installed successfully.

# CentOS 7 InitScripts
- name: Add CentOS 7 InitScripts repository
  yum_repository:
    name: initscripts_repo
    description: CentOS 7 InitScripts Package Repository
    baseurl: http://mirror.centos.org/centos/7/os/x86_64/
- name: Import CentOS 7 InitScritps GPG key 
  rpm_key:  
    state: present 
    key: http://mirror.centos.org/centos/7/os/x86_64/RPM-GPG-KEY-CentOS-7
- name: Install CentOS 7 InitScritps
  yum:
    name: initscripts-9.49.47-1.el7.x86_64
    state: present
- name: Display debug information
  debug:
    msg: centos 7 initscripts installed successfully.

## Docker
#- name: Add Docker repository
#  yum_repository:
#    name: docker_repo
#    description: Docker Package Repository
#    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
#- name: Import Docker GPG key 
#  rpm_key:  
#    state: present 
#    key: https://download.docker.com/linux/centos/gpg
#- name: Install Docker 
#  yum:
#    name: docker-ce-18.09.9-3.el7.x86_64
#    state: present
#- name: Display debug information
#  debug:
#    msg: docker 18.09.9 installed successfully.

## Kubectl
#- name: Add Kubernetes repository
#  yum_repository:
#    name: kubernetes_repo
#    description: Kubernetes Package Repository
#    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/
#- name: Import Kubernetes GPG key
#  rpm_key:
#    state: present
#    key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
#- name: Install Kubectl
#  yum:
#    name: kubectl-1.10.3-0.x86_64 
#    state: present
#- name: Display debug information
#  debug:
#    msg: kubectl 1.10.3 installed successfully.

## Helm
#- name: Create temporal folder
#  file:
#    path: /tmp/aws-devops/helm
#    state: directory
#- name: Download helm binary
#  unarchive:
#    src: https://get.helm.sh/helm-v2.7.2-linux-amd64.tar.gz
#    dest: /tmp/aws-devops/helm
#    creates: /usr/local/bin/helm
#    remote_src: yes
#- name: Move helm binary into place.
#  command:
#    cmd: cp /tmp/aws-devops/helm/linux-amd64/helm /usr/local/bin/helm
#    creates: /usr/local/bin/helm
#- name: Display debug information
#  debug:
#    msg: helm 2.7.2 installed successfully.

## Terraform
#- name: Create temporal folder
#  file:
#    path: /tmp/aws-devops/terraform
#    state: directory
#- name: Download helm binary
#  unarchive:
#    src: https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_freebsd_amd64.zip
#    dest: /tmp/aws-devops/terraform
#    creates: /usr/local/bin/terraform
#    remote_src: yes
#- name: Move helm binary into place.
#  command:
#    cmd: cp /tmp/aws-devops/terraform/terraform /usr/local/bin/terraform
#    creates: /usr/local/bin/terraform
#- name: Display debug information
#  debug:
#    msg: terraform 0.12.20 installed successfully.

## AWS
#- name: Download AWS binary
#  unarchive:
#    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
#    dest: /root
#    creates: /root/.aws
#    remote_src: yes
#- name: Executes the AWS installer.
#  command:
#    cmd: /root/aws/install
#    creates: /root/.aws
#- name: Display debug information
#  debug:
#    msg: aws cli 2.0 installed successfully.

# Jenkins
- name: Removing java 1.7.0
  yum:
    name: java-1.7.0-openjdk
    state: absent
- name: Install java 1.8.0
  yum:
    name: java-1.8.0-openjdk
    state: present
- name: Add Jenkins repository
  yum_repository:
    name: jenkins_repo
    description: Jenkins Package Repository
    baseurl: https://pkg.jenkins.io/redhat/
- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key
- name: Install Jenkins
  yum:
    name: jenkins-2.220-1.1.noarch
    state: present
- name: Start Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started
- name: Display debug information
  debug:
    msg: jenkins 2.220 installed successfully.