---
# Install the AWS CLI tool

- name: Download the AWS CLI binary zip file
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /root
    remote_src: yes
    creates: /usr/local/bin/aws

- name: Execute the AWS installer
  command:
    cmd: /root/aws/install
    creates: /usr/local/bin/aws