---
# Install the CentOS 7 InitScripts (which are required by Jenkins)

- name: Add the CentOS 7 InitScripts yum repository
  yum_repository:
    name: initscripts_repo
    description: CentOS 7 InitScripts Package Repository
    baseurl: http://mirror.centos.org/centos/7/os/x86_64/
    state: present

- name: Import the CentOS 7 InitScritps repository GPG key
  rpm_key:
    key: http://mirror.centos.org/centos/7/os/x86_64/RPM-GPG-KEY-CentOS-7
    state: present

- name: Install the CentOS 7 InitScritps package
  yum:
    name: initscripts-9.49.47-1.el7.x86_64
    state: present